### ISSUE TITLE
Communication issues?

### ISSUE THREAD

**Issue by freshwuzhere** [FlyingDiver/Indigo-BondHome#11]
Hi,

Love all your plugins - this one too - but performance has degraded lately with following response to request to configure:-

 Error (client)                  timeout waiting for plugin response from com.flyingdiver.indigoplugin.bondhome for request UiGetValues1
   Error (client)                  timeout waiting for plugin response from com.flyingdiver.indigoplugin.bondhome for request CallPluginFunc
   Error (client)                  runConfigDialog() caught exception: NSInvalidArgumentException -- *** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]

Any thoughts?  I'm not sure it's the plugins fault.   V2022.0.4 (and V2022.0.3 also).  Latest Indigo release.

**Comment by FlyingDiver** [comment]
That's from trying to open the plugin's config dialog?  From the plugin menu?  Or are you trying to edit a device?

**Comment by freshwuzhere** [comment]
That is from trying to open the plugin Config dialog.   I have identified an issue when **both** ethernet AND wifi are connected.  I am having better luck with reset network on ethernet only.   Still getting a LONG delay with the shades but they are responding now and dialogs eventually open.  Think it is all about communications (small demo python program I wrote works perfectly

**Comment by FlyingDiver** [comment]
Yeah, having both enabled on the Indigo server is known to cause issues.

**Comment by freshwuzhere** [comment]
Thanks! sorry to disturb!
