### ISSUE TITLE
IncreaseSpeed action failing

### ISSUE THREAD

**Issue by vvrangler** [FlyingDiver/Indigo-BondHome#12]
When issuing IncreaseSpeed action, without a parameter the action results in Bad Request

```
   Bond Home Debug                 device_action, url = http://192.168.100.194/v2/devices/5c0x47x83xa69x58/actions/DecreaseSpeed, payload = {}
   Bond Home Debug                 device_action, resp = <Response [200]>
   Bond Home Debug                 device_action, url = http://192.168.100.194/v2/devices/5c0x47x83xa69x58/actions/IncreaseSpeed, payload = {}
   Bond Home Error                 Error in plugin execution ExecuteAction:

  File "plugin.py", line 379, in actionControlDevice
  File "/Library/Application Support/Perceptive Automation/Indigo 2022.2/Plugins/BondHome.indigoPlugin/Contents/Server Plugin/bondhome.py", line 84, in device_action
  File "/Library/Application Support/Perceptive Automation/Indigo 2022.2/IndigoPluginHost3.app/Contents/Resources/PlugIns/requests/models.py", line 960, in raise_for_status
type: 400 Client Error: Bad Request for url: http://192.168.100.194/v2/devices/5c0x47x83xa69x58/actions/IncreaseSpeed

```

The same action with a parameter works

```
   Bond Home Debug                 device_action, url = http://192.168.1.94/v2/devices/5c04f76833a69d58/actions/IncreaseSpeed, payload = {'argument': 1}
   Bond Home Debug                 device_action, resp = <Response [200]>
   Bond Home Debug                 device_action, url = http://192.168.1.94/v2/devices/5c04f76833a69d58/actions/TurnOff, payload = {}
   Bond Home Debug                 device_action, resp = <Response [200]>
   Bond Home Debug                 device_action, url = http://192.168.1.94/v2/devices/5c04f76833a69d58/actions/IncreaseSpeed, payload = {'argument': 3}
   Bond Home Debug                 device_action, resp = <Response [200]>
   Bond Home Debug                 device_action, url = http://192.168.1.94/v2/devices/5c04f76833a69d58/actions/TurnOff, payload = {}
   Bond Home Debug                 device_action, resp = <Response [200]>

```

It looks like the v3 API docs show the speed actions including a parameter.

Actions

SetSpeed(speed): Set speed and turn on. If speed>max_speed, max_speed is assumed. If the fan is off, implicitly turn on the power. Setting speed to zero or a negative value is ignored.

IncreaseSpeed(speeds): Increase speed of fan by specified number of speeds. If the fan is off, implicitly turn on the power.

DecreaseSpeed(speeds): Decrease fan speed by specified number of speeds. If attempting to decrease fan speed below 1, the fan will remain at speed 1. That is, power will not be implicitly turned off. If the power is already off, DecreaseSpeed is ignored.

**Comment by FlyingDiver** [comment]
I'm not sure what I can do different.  It's really up to the user to know what actions need parameters or not.  Those actions are fetched at run time from the Bond, so I can't code parameter requirements into the plugin.

**Comment by vvrangler** [comment]
![image](https://user-images.githubusercontent.com/59268098/222173440-e2c9ae3a-0254-473e-9a04-2e4c385f711d.png)

I failed to mention that while creating an Action for the IncreaseSpeed and passing a parameter it works as intended, it's when I try to setup a device to use for increasing/decreasing the speed that I have an issue as there is no place to add a parameter.

**Comment by FlyingDiver** [comment]
Ah, I see.  Until I can add that, you could create a virtual device using action groups that use the action command with the parameter.

**Comment by vvrangler** [comment]
Will do, thanks again for another great plugin!

**Comment by FlyingDiver** [comment]
Try https://github.com/FlyingDiver/Indigo-BondHome/releases/tag/2022.1.0

Now has parameter fields for on/off commands.

**Comment by FlyingDiver** [comment]
Releasing version with parameter support.
