### ISSUE TITLE
issue adding fireplace remote

### ISSUE THREAD

**Issue by techliege** [FlyingDiver/Indigo-BondHome#14]
I get errors in creating a fireplace remote. 
see attached file for copies of the logs. I didn't restart the plugin till after it was added. if that is a problem let me know. 
I did reload after and it is at the end of the file. 
two files (same data) for your convenience in the zip. an rtf one (Mac) and a word file. 
[bond fireplace remote.zip](https://github.com/FlyingDiver/Indigo-BondHome/files/12841440/bond.fireplace.remote.zip)

**Comment by FlyingDiver** [comment]
One problem is that I assumed the 'flame' state would always be present for a fireplace, but yours does not have it.  Is your fireplace single stage only?  What controls does it have?

**Comment by FlyingDiver** [comment]
Another problem is that there must have been some API or firmware change, because my fireplace device is throwing an error when I try to turn it on, but it turns off just fine.  So I need to figure out what's going on there.

Might be a few days before I can dig into this.

**Comment by techliege** [comment]
it only has on and off.  no flame control or fan control.
not in a hurry. is actually a new fireplace, so just getting around to adding it.

**Comment by FlyingDiver** [comment]
I figured out the problem with my fireplace.  Mine has an off and "increase flame" button.  The fireplace as a "light only" mode (electric, no heat), and 2 or three levels of heat.  The API now requires a number parameter for "Increase flame", which wasn't required before (defaulted to 1).

I'll need to update the plugin to deal with fireplaces that are only on/off, no flame parameter.

**Comment by techliege** [comment]
OK. like I said. no hurry. in case you are curious, the flame control on mine is manual and there is no fan. the flame control adjusts the gas flow coming in.

**Comment by FlyingDiver** [comment]
I figured it was something like that.  Yours is gas, mine is electric. :)

**Comment by FlyingDiver** [comment]
Try https://github.com/FlyingDiver/Indigo-BondHome/releases/tag/2022.1.3

**Comment by techliege** [comment]
don't see any errors. is it supposed to look like this (attached screen shot of Fireplace)? it looks like a switch with on/off (always has)? that value didn't update when I turned it on and off. it did update the bond app.

![Screenshot 2023-10-08 at 4 33 22 PM](https://github.com/FlyingDiver/Indigo-BondHome/assets/147341932/adbd2f9e-749b-496d-bfb1-0a2dd3e151e6)

**Comment by FlyingDiver** [comment]
Yeah, that looks right.

The plugin is supposed to update the state when the Bond sends out a status update (instead of assuming the command worked).  But that part of the code doesn't seem to be working right.  I have an issue open on it, but have not had an opportunity to dig into it and figure out why it's not working.

**Comment by techliege** [comment]
ok. thanks!!
