### ISSUE TITLE
Auto-convert device types

### ISSUE THREAD

**Issue by FlyingDiver** [FlyingDiver/Indigo-BondHome#6]
Convert old types to new ones.

**Comment by EagleyeI** [comment]
Joe,

Just wondering how the fix door this plug-in is progressing?

**Comment by EagleyeI** [comment]
*for not door

**Comment by FlyingDiver** [comment]
This one is low priority after the other issues for this plugin.  I need to get the new types working correctly before I come back to this one.

**Comment by EagleyeI** [comment]
Thanks Joe,

I look forward to see an update in the near future, so as I can re-capture the operation of my ceiling fans via Indigo.

Regards.....

 John Nielsen
John Nielsen
PO Box 1101,
Glen Waverley, 3150, VIC
M: +61 3 419 529 796
E: ***@***.******@***.***>


From: Joe Keenan ***@***.***>
Reply to: FlyingDiver/Indigo-BondHome ***@***.***>
Date: Wednesday, 21 July 2021 at 12:58 am
To: FlyingDiver/Indigo-BondHome ***@***.***>
Cc: John Nielsen ***@***.***>, Manual ***@***.***>
Subject: Re: [FlyingDiver/Indigo-BondHome] Auto-convert device types (#6)


This one is low priority after the other issues for this plugin. I need to get the new types working correctly before I come back to this one.

**Comment by FlyingDiver** [comment]
You can't go back to an older version of the plugin?

**Comment by EagleyeI** [comment]
Joe,

If that will fix the issue, I can try this.

Regards.....

 John Nielsen
John Nielsen
PO Box 1101,
Glen Waverley, 3150, VIC
M: +61 3 419 529 796
E: ***@***.******@***.***>


From: Joe Keenan ***@***.***>
Reply to: FlyingDiver/Indigo-BondHome ***@***.***>
Date: Wednesday, 21 July 2021 at 8:34 am
To: FlyingDiver/Indigo-BondHome ***@***.***>
Cc: John Nielsen ***@***.***>, Manual ***@***.***>
Subject: Re: [FlyingDiver/Indigo-BondHome] Auto-convert device types (#6)


You can't go back to an older version of the plugin?

**Comment by FlyingDiver** [comment]
I'm not sure I'm going to be able to fix this properly.  You might have to re-create your fan devices.

**Comment by EagleyeI** [comment]
Thanks Joe,  I re-established the Bond Home Bridge, which seems to have worked.  I now have full visibility to all Bond Home options, and I have been able to successfully re-connect all my devices.  Interestingly, the Bond Home Bridge is now showing as a dimmable device, which was not the case previously.

Regards.....

 John Nielsen
John Nielsen
PO Box 1101,
Glen Waverley, 3150, VIC
M: +61 3 419 529 796
E: ***@***.******@***.***>


From: Joe Keenan ***@***.***>
Reply to: FlyingDiver/Indigo-BondHome ***@***.***>
Date: Thursday, 22 July 2021 at 7:14 am
To: FlyingDiver/Indigo-BondHome ***@***.***>
Cc: John Nielsen ***@***.***>, Manual ***@***.***>
Subject: Re: [FlyingDiver/Indigo-BondHome] Auto-convert device types (#6)


I'm not sure I'm going to be able to fix this properly. You might have to re-create your fan devices.

**Comment by FlyingDiver** [comment]
Yeah, that's the blue light on the front.  :)
