### ISSUE TITLE
2022.0.1 Info

### ISSUE THREAD

**Issue by Koreysherwin** [FlyingDiver/Indigo-BondHome#9]
upon startup:

`   Debugging plugin "Bond Home 2022.0.1" (pid 68190)
   Bond Home Error                 Error in plugin execution InitializeMain:

  File "plugin.py", line 10, in <module>
type: No module named 'zeroconf'

   Stopping plugin "Bond Home 2022.0.1" (pid 68190)
   Stopped plugin "Bond Home 2022.0.1" 
`

**Comment by FlyingDiver** [comment]
That looks like a mix of two different log files.  Can you restart the plugin and just post one of them?

**Comment by FlyingDiver** [comment]
OK, that's something totally different.

**Comment by Koreysherwin** [comment]
this is from the indigo log:

`   Started plugin "Bond Home 2022.0.1"
   Bond Home                       Starting BondHome
   Bond Home                       Bond Bridge: Starting bondBridge Device 1731641810
   Bond Home                       Family Room - Celing Fan: Starting bondDevice Device 656058716
   Bond Home                       Family Room - Fan: Starting smartBond Device 806306447
   Bond Home Error                 Error in plugin execution _postStartup:

  File "plugin.py", line 234, in _postStartup
  File "plugin.py", line 186, in doDeviceStartup
type: 'NoneType' object has no attribute 'get'
`

**Comment by Koreysherwin** [comment]
[plugin.log](https://github.com/FlyingDiver/Indigo-BondHome/files/9085731/plugin.log)

**Comment by Koreysherwin** [comment]
this one should be clearer, I deleted the log and started fresh:

[plugin.log](https://github.com/FlyingDiver/Indigo-BondHome/files/9085767/plugin.log)

**Comment by Koreysherwin** [comment]
This is what appears in the terminal window with debug turned on:

`Last login: Mon Jul 11 09:03:44 on ttys001
/Library/Application\ Support/Perceptive\ Automation/Indigo\ 2022.1/.debugPluginLaunch.command ; exit;
Indigo:~ indigo$ /Library/Application\ Support/Perceptive\ Automation/Indigo\ 2022.1/.debugPluginLaunch.command ; exit;



















Starting PuDB debugging of plugin BondHome.indigoPlugin.
To set breakpoints add indigo.debugger() calls and reload debugger.

Exception in thread Thread-3 (udp_receive):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Application Support/Perceptive Automation/Indigo 2022.1/Plugins/BondHome.indigoPlugin/Contents/Server Plugin/bondhome.py", line 59, in udp_receive
    self.sock.sendto('\n', (self.address, 30007))
TypeError: a bytes-like object is required, not 'str'
Exception in thread Thread-4 (udp_receive):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Application Support/Perceptive Automation/Indigo 2022.1/Plugins/BondHome.indigoPlugin/Contents/Server Plugin/bondhome.py", line 59, in udp_receive
    self.sock.sendto('\n', (self.address, 30007))
TypeError: a bytes-like object is required, not 'str'

`

**Comment by FlyingDiver** [comment]
That's a restart in the debugger, not debug logging.  Debug logging is enabled in the plugin config dialog.

There's something messed up with your 'Family Room - Celing Fan' device.  Please use the right click context menu on the device to 'Print Device Details to Log' and post that.

**Comment by Koreysherwin** [comment]
Seems that was the issue, I deleted the device and no more Errors!

**Comment by FlyingDiver** [comment]
Yeah.  Something changed that, which broke things.  I've added code to account for device addresses not found.  Also for the error you were seeing in the debugger.  Hold on while I upload it.

**Comment by Koreysherwin** [comment]
`   Debugging plugin "Bond Home 2022.0.2" (pid 81778)
   Bond Home Debug                 logLevel = 5
   Started plugin "Bond Home 2022.0.2"
   Bond Home                       Starting BondHome
   Bond Home                       Bond Bridge: Starting bondBridge Device 1731641810
   Bond Home Debug                 BondHome __init__ address = 192.168.0.32, token = 9be70fea84308e41
   Bond Home Debug                 Service KSMWWDH99949._bond._tcp.local. of type _bond._tcp.local. state changed: ServiceStateChange.Added
   Bond Home Debug                 Found BondBridges: {'KSMWWDH99949._bond._tcp.local.': 'KSMWWDH99949.local.'}
   Bond Home Debug                 Bond Bridge: Bond version: {'target': 'zermatt', 'fw_ver': 'v3.3.8-beta', 'fw_date': 'Sun Jul 10 18:59:22 UTC 2022', 'uptime_s': 64313, 'make': 'Olibra', 'model': 'BD-1000', 'branding_profile': 'OLIBRA_BD1000', 'bondid': 'ZZDE62994', 'upgrade_http': True, 'api': 2, '_': 'eb4732df', '__': 'eb4732df'}
   Bond Home Debug                 Bond Bridge: Bond info: {'name': 'My Bridge', 'location': 'Office', 'bluelight': 0, 'frequencies': [[38, 38], [300000, 321500], [336000, 399500], [410500, 450000]], '_': 'c436f627', '__': 'c436f627'}
   Bond Home Debug                 get_device_list: {'_': 'a0391f60', '__': '00000000', '5fb2edac7c757ffe': {'_': '43a15664'}}
   Bond Home Debug                 Bond Bridge: known_devices:
{'ZZDE62994': {'5fb2edac7c757ffe': {'name': 'Fan Remote', 'type': 'CF', 'location': 'Family Room', 'template': 'A3a', 'actions': ['DecreaseSpeed', 'IncreaseSpeed', 'SetDirection', 'SetSpeed', 'StartDimmer', 'Stop', 'ToggleDirection', 'ToggleLight', 'TogglePower', 'TurnLightOff', 'TurnLightOn', 'TurnOff', 'TurnOn'], '_': '43a15664', '__': '9ba44dfc', 'commands': {'_': 'daff0f99'}, 'state': {'_': 'b4766ac1'}, 'properties': {'_': 'e48b1425'}, 'skeds': {'_': '00000000'}}}}
   Bond Home Debug                 udp_start() socket listener started
   Bond Home                       Family Room - Fan: Starting smartBond Device 806306447
   Bond Home Debug                 BondHome __init__ address = 192.168.0.31, token = 2981f39b1e84b299
   Bond Home Debug                 Service ZZDE62994._bond._tcp.local. of type _bond._tcp.local. state changed: ServiceStateChange.Added
   Bond Home Debug                 Found BondBridges: {'KSMWWDH99949._bond._tcp.local.': 'KSMWWDH99949.local.', 'ZZDE62994._bond._tcp.local.': 'ZZDE62994.local.'}
   Bond Home Debug                 Family Room - Fan: BondHome version: {'target': 'breck-spitfire', 'fw_ver': 'v3.2.4-beta', 'fw_date': 'Fri Jun 10 14:25:55 UTC 2022', 'uptime_s': 89965, 'make': 'Minka Aire', 'model': 'F868L', 'branding_profile': 'MINKA_F868L', 'bondid': 'KSMWWDH99949', 'upgrade_http': True, 'api': 2, '_': '9a0974d3', '__': '9a0974d3'}
   Bond Home Debug                 get_device_list: {'_': '04127b18', '__': '00000000', '1': {'_': 'c6377d91'}}
   Bond Home Debug                 Family Room - Fan: known_devices:
{'ZZDE62994': {'5fb2edac7c757ffe': {'name': 'Fan Remote', 'type': 'CF', 'location': 'Family Room', 'template': 'A3a', 'actions': ['DecreaseSpeed', 'IncreaseSpeed', 'SetDirection', 'SetSpeed', 'StartDimmer', 'Stop', 'ToggleDirection', 'ToggleLight', 'TogglePower', 'TurnLightOff', 'TurnLightOn', 'TurnOff', 'TurnOn'], '_': '43a15664', '__': '9ba44dfc', 'commands': {'_': 'daff0f99'}, 'state': {'_': 'b4766ac1'}, 'properties': {'_': 'e48b1425'}, 'skeds': {'_': '00000000'}}}, 'KSMWWDH99949': {'1': {'name': 'Fan', 'location': 'Family Room', 'type': 'CF', 'actions': ['TurnOn', 'TurnOff', 'TogglePower', 'SetSpeed', 'IncreaseSpeed', 'DecreaseSpeed', 'TurnLightOn', 'TurnLightOff', 'ToggleLight', 'SetBrightness', 'IncreaseBrightness', 'DecreaseBrightness', 'CycleBrightness', 'SetTimer', 'BreezeOn', 'BreezeOff', 'SetBreeze', 'SetDirection', 'ToggleDirection'], '_': 'c6377d91', '__': '14ac779b', 'state': {'_': '7cc7b735'}, 'properties': {'_': '3569eb3a'}, 'skeds': {'_': '00000000'}, 'power_cycle_state': {'_': '857a5c59'}, 'addr': {'_': '613ab7e5'}}}}
   Bond Home Debug                 udp_start() socket listener started
   Bond Home                       Fan Remote (5fb2edac7c757ffe): Starting bondDevice Device 1285702161
   Bond Home Debug                 Fan Remote (5fb2edac7c757ffe): doDeviceStartup: bondDevice (5fb2edac7c757ffe)
   Bond Home Debug                 Fan Remote (5fb2edac7c757ffe): doDeviceStartup: using bond_id = ZZDE62994
   Bond Home Debug                 Fan Remote (5fb2edac7c757ffe): Device states: {'power': 1, 'speed': 3, 'direction': 1, 'light': 0, '_': 'b4766ac1', '__': 'b4766ac1'}
   Bond Home Error                 Error in plugin execution _postStartup:

  File "plugin.py", line 239, in _postStartup
  File "plugin.py", line 209, in doDeviceStartup
type: local variable 'bond_type' referenced before assignment`

**Comment by Koreysherwin** [comment]
strange, I was using the <> option in the editor

**Comment by FlyingDiver** [comment]
Weird.
